# Generated by Django 5.2 on 2025-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0002_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('INIT', 'init'), ('IN_PROGRESS', 'in_progress'), ('FINISHED', 'finished')], default='init'),
        ),
    ]
