# Generated by Django 5.2 on 2025-11-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_alter_challenge_athlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
