# Generated by Django 5.2 on 2025-11-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_remove_challenge_athlete_challenge_athlete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longtitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
    ]
