# Generated by Django 5.2 on 2025-11-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0016_alter_position_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
