# Generated by Django 5.2 on 2025-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0018_run_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('uid', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('picture', models.URLField()),
                ('value', models.IntegerField()),
            ],
        ),
    ]
