# Generated by Django 5.2 on 2025-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_position_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True),
        ),
    ]
